;;; Code:
(define-skeleton skeleton-math-letter
  "Inserts a latex Letter Outline into the buffer"
  "Title: "
  "\\documentclass[11pt, oneside, fullpage]{article}\n"
  "\\usepackage{geometry}\n"
  "\\geometry{letterpaper}\n"
  "\\usepackage{graphicx}\n"
  "\\usepackage{amssymb}\n"
  "\\usepackage{enumitem}\n"
  "\\usepackage{amsmath}\n"
  "\\usepackage{amsfonts}\n"
  "\\makeatletter\n"
  "\\newcommand{\\zz}{\\mathbb{Z}}\n"
  "\\newcommand{\\rr}{\\mathbb{R}}\n"
  "\\newcommand{\\cc}{\\mathbb{C}}\n"
  "\\newcommand{\\nsum}{\\sum^n_{i=1}}\n"
  "\\newcommand{\\qq}{\\mathbb{Q}}\n"
  "\\newcommand{\\nn}{\\mathbb{N}}\n"
  "\\newcommand{\\exc}[1]{$ $\\\\\\noindent\\textbf{Problem #1}}\n"
  "\\newcommand{\\inpr}[2]{\\langle #1, #2\\rangle}\n"
  "\\newcommand{\\floor}[1]{\\lfloor #1 \\rfloor}\n"
  "\\newcommand{\\ceil}[1]{\\lceil #1 \\rceil}\n"
  "\\newcommand{\\bmatrix}[1]{\\begin{bmatrix}#1\\end{bmatrix}}\n"
  "\\newcommand{\\fl}{{\\mathcal L}}\n"
  "\\newcommand{\\fu}{{\\mathcal U}}\n"
  "\\usepackage{tikz}\n"
  "\\title{" (skeleton-read "Title: ") "\n"
  "  \\\\ \\large " (skeleton-read "Class: ") "}\n"
  "\\author{" user-full-name "}\n"
  "\\date{" (skeleton-read "Date: ") "}\n"
  "\\begin{document}\n"
  "\\maketitle\n"
  "$\n"
  "$\\\\\n"
  -
  "\n\n\n\\end{document}"
  )

(define-skeleton skeleton-krumm-math-homework
  "Math homework framework for David Krumm: Math 332"
  "head"
  "\\documentclass[12pt,oneside]{amsart}\n"
  "\\usepackage{amsmath,amssymb}\n"
  "\\usepackage{graphicx,enumerate,enumitem}\n"
  "\n"
  "\\theoremstyle{definition}\n"
  "\\newtheorem{prob}{Problem}\n"
  "\n"
  "\\DeclareMathOperator{\\lcm}{lcm}\n"
  "\\newcommand{\\N}{\\mathbb N}\n"
  "\\newcommand{\\Z}{\\mathbb Z}\n"
  "\\newcommand{\\Q}{\\mathbb Q}\n"
  "\\newcommand{\\R}{\\mathbb R}\n"
  "\\newcommand{\\C}{\\mathbb C}\n"
  "\\renewcommand{\\epsilon}{\\varepsilon}\n"
  "\\newenvironment{solution}\n"
  "{\\renewcommand\\qedsymbol{$\\blacksquare$}\\begin{proof}[Solution:]}\n"
  "{\\end{proof}}\n"
  "\n"
  "\\begin{document}\n"
  "\\\\{\\Huge Math 332 Homework Assignment\\\\}\n"
  "\\\\\n"
  "\\\\\n"
  "\\\\{\\LARGE Name: Ian Wahbe \\\\}\n"
  "\\\\\n"
  "\\\\{\\LARGE Assignment Number: " (skeleton-read "Assignment Number: ") " \\\\}\n"
  "\\\\\n"
  "\\\\{\\LARGE Collaborators: " (skeleton-read "Collaborators: ") " \\\\}\n"
  "\\newpage\n"
  "\n"
  "\\begin{prob}[" (skeleton-read "First Problem: ") "]\n"
  -
  "\n"
  "\\end{prob}\n"
  "\\begin{solution}\n"
  "\n"
  "\\end{solution}\n"
  "\\end{document}\n"
  )

(define-skeleton skeleton-algorthims-howework
  "CS homework framework for Adam Groce: CSCI382"
  "head"
  "\\documentclass[12pt,oneside]{amsart}\n"
  "\\usepackage{amsmath,amssymb}\n"
  "\\usepackage{graphicx,enumerate,enumitem}\n"
  "\n"
  "%Algorithm2e\n"
  "\\usepackage{algorithm2e}\n"
  "\\RestyleAlgo{algoruled}\n"
  "\\newcommand{\\xAlCapSty}[1]{\\small\\sffamily\\bfseries\\MakeUppercase{#1}}\n"
  "\\newcommand{\\AlgTitle}[1]{\\caption{\\small\\sffamily\\bfseries #1:}}\n"
  "\\newcommand{\\makecaption}[1]{\\caption{\\small\\sffamily\\bfseries\\MakeUppercase{#1}:}}\n"
  "\\newcommand{\\mycommfont}[1]{\\footnotesize\\ttfamily{#1}}\n"
  "\\newcommand{\\cmt}[1]{\\Comment*[r]{#1}}\n"
  "\\SetCommentSty{mycommfont}\n"
  "\\LinesNumbered\n"
  "\\SetAlCapSty{xAlCapSty}\n"
  "\\NoCaptionOfAlgo % removes Algorithm: \n"
  "\\DontPrintSemicolon\n"
  "\n"
  "\\theoremstyle{definition}\n"
  "\\newtheorem{prob}{Problem}\n"
  "\n"
  "\\newcommand{\\N}{\\mathbb N}\n"
  "\\newcommand{\\Z}{\\mathbb Z}\n"
  "\\renewcommand{\\epsilon}{\\varepsilon}\n"
  "\\newcommand{\\V}[1]{\\texttt{\\MakeUppercase{#1}}}\n"
  "\\renewcommand{\\v}[1]{\\texttt{#1}}"
  "\\newenvironment{solution}\n"
  "{\\renewcommand\\qedsymbol{$\\blacksquare$}\\begin{proof}[Solution:]}\n"
  "{\\end{proof}}\n"
  "\\title[]{%\n"
  "  \\huge MATH/CSCI 382 \\\\\n"
  "  \\large Homework " (skeleton-read "Assignment Number: ") "\\\\\n"
  "  \\normalsize Due " (skeleton-read "Due Date (Day, Month date): ") "}\n"
  "\\author[]{\\large Ian Wahbe}\n"
  "\n"
  "\\begin{document}\n"
  "\\maketitle\n"
  "\n"
  "\\begin{enumerate}[label=\\arabic*.]\n"
  "\\item\n"
  -
  "\n"
  "\\end{enumerate}\n"
  "\n"
  "\\end{document}\n"
  )


(define-skeleton skeleton-krumm-problem
  "Problem for David Krumm"
  "head"
  "\\begin{prob}[" (skeleton-read "Problem: ") "]\n"
  -
  "\n"
  "\\end{prob}\n"
  "\\begin{solution}\n"
  "\n"
  "\n"
  "\\end{solution}\n"
  )


(provide 'LaTeX_skeletons)
;;; LaTeX_skeletons ends here
